<?php
/**
 * CreateBalanceExportRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  com.layer1.clients.digital.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Digital Asset
 *
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace com.layer1.clients.digital.invoker\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateBalanceExportRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateBalanceExportRequest
 * @package     com.layer1.clients.digital.invoker
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateBalanceExportRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateBalanceExportRequest"
     */
    public function testCreateBalanceExportRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "network"
     */
    public function testPropertyNetwork()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "asset"
     */
    public function testPropertyAsset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "networks"
     */
    public function testPropertyNetworks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "assets"
     */
    public function testPropertyAssets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "asset_pool_id"
     */
    public function testPropertyAssetPoolId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
