<?php
/**
 * AddressApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  com.layer1.clients.digital.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Digital Asset
 *
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace com.layer1.clients.digital.invoker\Test\Api;

use \com.layer1.clients.digital.invoker\Configuration;
use \com.layer1.clients.digital.invoker\ApiException;
use \com.layer1.clients.digital.invoker\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AddressApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.layer1.clients.digital.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAddress
     *
     * Create a new address.
     *
     */
    public function testCreateAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAddress
     *
     * Get address.
     *
     */
    public function testGetAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAddresses
     *
     * List addresses.
     *
     */
    public function testListAddresses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTags
     *
     * List address tags.
     *
     */
    public function testListTags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for validateAddress
     *
     * Validate address.
     *
     */
    public function testValidateAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
