<?php
/**
 * TransactionRequestApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  com.layer1.clients.digital.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Digital Asset
 *
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace com.layer1.clients.digital.invoker\Test\Api;

use \com.layer1.clients.digital.invoker\Configuration;
use \com.layer1.clients.digital.invoker\ApiException;
use \com.layer1.clients.digital.invoker\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionRequestApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.layer1.clients.digital.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionRequestApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createStakingTransaction
     *
     * Create staking transaction request.
     *
     */
    public function testCreateStakingTransaction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTransaction
     *
     * Create transaction request.
     *
     */
    public function testCreateTransaction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTransactionRequestById
     *
     * Get transaction request.
     *
     */
    public function testGetTransactionRequestById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTransactionRequests
     *
     * List transaction requests.
     *
     */
    public function testListTransactionRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
