<?php
/**
 * AddressApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Layer1ClientsDigitalInvoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Digital Asset
 *
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Layer1ClientsDigitalInvoker\Layer1ClientsDigitalApi;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Layer1ClientsDigitalInvoker\ApiException;
use Layer1ClientsDigitalInvoker\Configuration;
use Layer1ClientsDigitalInvoker\FormDataProcessor;
use Layer1ClientsDigitalInvoker\HeaderSelector;
use Layer1ClientsDigitalInvoker\ObjectSerializer;

/**
 * AddressApi Class Doc Comment
 *
 * @category Class
 * @package  Layer1ClientsDigitalInvoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AddressApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createAddress' => [
            'application/json',
        ],
        'getAddress' => [
            'application/json',
        ],
        'listAddresses' => [
            'application/json',
        ],
        'listTags' => [
            'application/json',
        ],
        'validateAddress' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAddress
     *
     * Create a new address
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateAddressRequest $create_address_request create_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function createAddress($create_address_request, string $contentType = self::contentTypes['createAddress'][0])
    {
        list($response) = $this->createAddressWithHttpInfo($create_address_request, $contentType);
        return $response;
    }

    /**
     * Operation createAddressWithHttpInfo
     *
     * Create a new address
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateAddressRequest $create_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAddressWithHttpInfo($create_address_request, string $contentType = self::contentTypes['createAddress'][0])
    {
        $request = $this->createAddressRequest($create_address_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address',
                        $request,
                        $response,
                    );
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createAddressAsync
     *
     * Create a new address
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateAddressRequest $create_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAddressAsync($create_address_request, string $contentType = self::contentTypes['createAddress'][0])
    {
        return $this->createAddressAsyncWithHttpInfo($create_address_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAddressAsyncWithHttpInfo
     *
     * Create a new address
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateAddressRequest $create_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAddressAsyncWithHttpInfo($create_address_request, string $contentType = self::contentTypes['createAddress'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address';
        $request = $this->createAddressRequest($create_address_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAddress'
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateAddressRequest $create_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createAddressRequest($create_address_request, string $contentType = self::contentTypes['createAddress'][0])
    {

        // verify the required parameter 'create_address_request' is set
        if ($create_address_request === null || (is_array($create_address_request) && count($create_address_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_address_request when calling createAddress'
            );
        }


        $resourcePath = '/digital/v1/addresses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_address_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_address_request));
            } else {
                $httpBody = $create_address_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAddress
     *
     * Get address
     *
     * @param  string $address_id address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address[]|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function getAddress($address_id, string $contentType = self::contentTypes['getAddress'][0])
    {
        list($response) = $this->getAddressWithHttpInfo($address_id, $contentType);
        return $response;
    }

    /**
     * Operation getAddressWithHttpInfo
     *
     * Get address
     *
     * @param  string $address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address[]|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAddressWithHttpInfo($address_id, string $contentType = self::contentTypes['getAddress'][0])
    {
        $request = $this->getAddressRequest($address_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address[]',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAddressAsync
     *
     * Get address
     *
     * @param  string $address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressAsync($address_id, string $contentType = self::contentTypes['getAddress'][0])
    {
        return $this->getAddressAsyncWithHttpInfo($address_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAddressAsyncWithHttpInfo
     *
     * Get address
     *
     * @param  string $address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAddressAsyncWithHttpInfo($address_id, string $contentType = self::contentTypes['getAddress'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Address[]';
        $request = $this->getAddressRequest($address_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAddress'
     *
     * @param  string $address_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAddressRequest($address_id, string $contentType = self::contentTypes['getAddress'][0])
    {

        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling getAddress'
            );
        }


        $resourcePath = '/digital/v1/addresses/{addressId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'addressId' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listAddresses
     *
     * List addresses
     *
     * @param  string $asset_pool_id asset_pool_id (required)
     * @param  int $page_number page_number (required)
     * @param  int $page_size page_size (required)
     * @param  string|null $q Query in lucene format. Supported fields: reference, customerId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function listAddresses($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listAddresses'][0])
    {
        list($response) = $this->listAddressesWithHttpInfo($asset_pool_id, $page_number, $page_size, $q, $contentType);
        return $response;
    }

    /**
     * Operation listAddressesWithHttpInfo
     *
     * List addresses
     *
     * @param  string $asset_pool_id (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string|null $q Query in lucene format. Supported fields: reference, customerId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listAddressesWithHttpInfo($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listAddresses'][0])
    {
        $request = $this->listAddressesRequest($asset_pool_id, $page_number, $page_size, $q, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listAddressesAsync
     *
     * List addresses
     *
     * @param  string $asset_pool_id (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string|null $q Query in lucene format. Supported fields: reference, customerId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAddressesAsync($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listAddresses'][0])
    {
        return $this->listAddressesAsyncWithHttpInfo($asset_pool_id, $page_number, $page_size, $q, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAddressesAsyncWithHttpInfo
     *
     * List addresses
     *
     * @param  string $asset_pool_id (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string|null $q Query in lucene format. Supported fields: reference, customerId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAddressesAsyncWithHttpInfo($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listAddresses'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress';
        $request = $this->listAddressesRequest($asset_pool_id, $page_number, $page_size, $q, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listAddresses'
     *
     * @param  string $asset_pool_id (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string|null $q Query in lucene format. Supported fields: reference, customerId (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listAddressesRequest($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listAddresses'][0])
    {

        // verify the required parameter 'asset_pool_id' is set
        if ($asset_pool_id === null || (is_array($asset_pool_id) && count($asset_pool_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $asset_pool_id when calling listAddresses'
            );
        }

        // verify the required parameter 'page_number' is set
        if ($page_number === null || (is_array($page_number) && count($page_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_number when calling listAddresses'
            );
        }
        if ($page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling AddressApi.listAddresses, must be bigger than or equal to 0.');
        }
        
        // verify the required parameter 'page_size' is set
        if ($page_size === null || (is_array($page_size) && count($page_size) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_size when calling listAddresses'
            );
        }
        if ($page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling AddressApi.listAddresses, must be smaller than or equal to 100.');
        }
        if ($page_size < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling AddressApi.listAddresses, must be bigger than or equal to 0.');
        }
        


        $resourcePath = '/digital/v1/addresses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $asset_pool_id,
            'assetPoolId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_number,
            'pageNumber', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listTags
     *
     * List address tags
     *
     * @param  string $address_id address_id (required)
     * @param  int $page_number page_number (required)
     * @param  int $page_size page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTags'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function listTags($address_id, $page_number, $page_size, string $contentType = self::contentTypes['listTags'][0])
    {
        list($response) = $this->listTagsWithHttpInfo($address_id, $page_number, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation listTagsWithHttpInfo
     *
     * List address tags
     *
     * @param  string $address_id (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTags'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listTagsWithHttpInfo($address_id, $page_number, $page_size, string $contentType = self::contentTypes['listTags'][0])
    {
        $request = $this->listTagsRequest($address_id, $page_number, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listTagsAsync
     *
     * List address tags
     *
     * @param  string $address_id (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTags'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listTagsAsync($address_id, $page_number, $page_size, string $contentType = self::contentTypes['listTags'][0])
    {
        return $this->listTagsAsyncWithHttpInfo($address_id, $page_number, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listTagsAsyncWithHttpInfo
     *
     * List address tags
     *
     * @param  string $address_id (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTags'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listTagsAsyncWithHttpInfo($address_id, $page_number, $page_size, string $contentType = self::contentTypes['listTags'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultAddress';
        $request = $this->listTagsRequest($address_id, $page_number, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listTags'
     *
     * @param  string $address_id (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTags'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listTagsRequest($address_id, $page_number, $page_size, string $contentType = self::contentTypes['listTags'][0])
    {

        // verify the required parameter 'address_id' is set
        if ($address_id === null || (is_array($address_id) && count($address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $address_id when calling listTags'
            );
        }

        // verify the required parameter 'page_number' is set
        if ($page_number === null || (is_array($page_number) && count($page_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_number when calling listTags'
            );
        }
        if ($page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling AddressApi.listTags, must be bigger than or equal to 0.');
        }
        
        // verify the required parameter 'page_size' is set
        if ($page_size === null || (is_array($page_size) && count($page_size) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_size when calling listTags'
            );
        }
        if ($page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling AddressApi.listTags, must be smaller than or equal to 100.');
        }
        if ($page_size < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling AddressApi.listTags, must be bigger than or equal to 0.');
        }
        

        $resourcePath = '/digital/v1/addresses/{addressId}/tags';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_number,
            'pageNumber', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);


        // path params
        if ($address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'addressId' . '}',
                ObjectSerializer::toPathValue($address_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation validateAddress
     *
     * Validate address
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressRequest $validate_address_request validate_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressResponse|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function validateAddress($validate_address_request, string $contentType = self::contentTypes['validateAddress'][0])
    {
        list($response) = $this->validateAddressWithHttpInfo($validate_address_request, $contentType);
        return $response;
    }

    /**
     * Operation validateAddressWithHttpInfo
     *
     * Validate address
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressRequest $validate_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressResponse|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function validateAddressWithHttpInfo($validate_address_request, string $contentType = self::contentTypes['validateAddress'][0])
    {
        $request = $this->validateAddressRequest($validate_address_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressResponse',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation validateAddressAsync
     *
     * Validate address
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressRequest $validate_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateAddressAsync($validate_address_request, string $contentType = self::contentTypes['validateAddress'][0])
    {
        return $this->validateAddressAsyncWithHttpInfo($validate_address_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation validateAddressAsyncWithHttpInfo
     *
     * Validate address
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressRequest $validate_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateAddressAsyncWithHttpInfo($validate_address_request, string $contentType = self::contentTypes['validateAddress'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressResponse';
        $request = $this->validateAddressRequest($validate_address_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'validateAddress'
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ValidateAddressRequest $validate_address_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function validateAddressRequest($validate_address_request, string $contentType = self::contentTypes['validateAddress'][0])
    {

        // verify the required parameter 'validate_address_request' is set
        if ($validate_address_request === null || (is_array($validate_address_request) && count($validate_address_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $validate_address_request when calling validateAddress'
            );
        }


        $resourcePath = '/digital/v1/addresses/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($validate_address_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($validate_address_request));
            } else {
                $httpBody = $validate_address_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
