<?php
/**
 * ExportApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Layer1ClientsDigitalInvoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Digital Asset
 *
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Layer1ClientsDigitalInvoker\Layer1ClientsDigitalApi;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Layer1ClientsDigitalInvoker\ApiException;
use Layer1ClientsDigitalInvoker\Configuration;
use Layer1ClientsDigitalInvoker\FormDataProcessor;
use Layer1ClientsDigitalInvoker\HeaderSelector;
use Layer1ClientsDigitalInvoker\ObjectSerializer;

/**
 * ExportApi Class Doc Comment
 *
 * @category Class
 * @package  Layer1ClientsDigitalInvoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExportApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createBalanceExport' => [
            'application/json',
        ],
        'getExport' => [
            'application/json',
        ],
        'getExports' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createBalanceExport
     *
     * Create a balance export
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateBalanceExportRequest $create_balance_export_request create_balance_export_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBalanceExport'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function createBalanceExport($create_balance_export_request, string $contentType = self::contentTypes['createBalanceExport'][0])
    {
        $this->createBalanceExportWithHttpInfo($create_balance_export_request, $contentType);
    }

    /**
     * Operation createBalanceExportWithHttpInfo
     *
     * Create a balance export
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateBalanceExportRequest $create_balance_export_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBalanceExport'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function createBalanceExportWithHttpInfo($create_balance_export_request, string $contentType = self::contentTypes['createBalanceExport'][0])
    {
        $request = $this->createBalanceExportRequest($create_balance_export_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createBalanceExportAsync
     *
     * Create a balance export
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateBalanceExportRequest $create_balance_export_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBalanceExport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBalanceExportAsync($create_balance_export_request, string $contentType = self::contentTypes['createBalanceExport'][0])
    {
        return $this->createBalanceExportAsyncWithHttpInfo($create_balance_export_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createBalanceExportAsyncWithHttpInfo
     *
     * Create a balance export
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateBalanceExportRequest $create_balance_export_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBalanceExport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBalanceExportAsyncWithHttpInfo($create_balance_export_request, string $contentType = self::contentTypes['createBalanceExport'][0])
    {
        $returnType = '';
        $request = $this->createBalanceExportRequest($create_balance_export_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createBalanceExport'
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateBalanceExportRequest $create_balance_export_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBalanceExport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createBalanceExportRequest($create_balance_export_request, string $contentType = self::contentTypes['createBalanceExport'][0])
    {

        // verify the required parameter 'create_balance_export_request' is set
        if ($create_balance_export_request === null || (is_array($create_balance_export_request) && count($create_balance_export_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_balance_export_request when calling createBalanceExport'
            );
        }


        $resourcePath = '/digital/v1/exports';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_balance_export_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_balance_export_request));
            } else {
                $httpBody = $create_balance_export_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getExport
     *
     * Get export with a download link
     *
     * @param  string $id The ID of the export to retrieve (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExport'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Export|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function getExport($id, string $contentType = self::contentTypes['getExport'][0])
    {
        list($response) = $this->getExportWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getExportWithHttpInfo
     *
     * Get export with a download link
     *
     * @param  string $id The ID of the export to retrieve (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExport'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Export|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getExportWithHttpInfo($id, string $contentType = self::contentTypes['getExport'][0])
    {
        $request = $this->getExportRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Export',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Export',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Export',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getExportAsync
     *
     * Get export with a download link
     *
     * @param  string $id The ID of the export to retrieve (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getExportAsync($id, string $contentType = self::contentTypes['getExport'][0])
    {
        return $this->getExportAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getExportAsyncWithHttpInfo
     *
     * Get export with a download link
     *
     * @param  string $id The ID of the export to retrieve (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getExportAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getExport'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\Export';
        $request = $this->getExportRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getExport'
     *
     * @param  string $id The ID of the export to retrieve (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExport'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getExportRequest($id, string $contentType = self::contentTypes['getExport'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getExport'
            );
        }


        $resourcePath = '/digital/v1/exports/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getExports
     *
     * List all exports
     *
     * @param  string[] $type Filter exports by type (required)
     * @param  int $page_number page_number (required)
     * @param  int $page_size page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExports'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedExports[]|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function getExports($type, $page_number, $page_size, string $contentType = self::contentTypes['getExports'][0])
    {
        list($response) = $this->getExportsWithHttpInfo($type, $page_number, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation getExportsWithHttpInfo
     *
     * List all exports
     *
     * @param  string[] $type Filter exports by type (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExports'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedExports[]|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getExportsWithHttpInfo($type, $page_number, $page_size, string $contentType = self::contentTypes['getExports'][0])
    {
        $request = $this->getExportsRequest($type, $page_number, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedExports[]',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedExports[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedExports[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getExportsAsync
     *
     * List all exports
     *
     * @param  string[] $type Filter exports by type (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExports'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getExportsAsync($type, $page_number, $page_size, string $contentType = self::contentTypes['getExports'][0])
    {
        return $this->getExportsAsyncWithHttpInfo($type, $page_number, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getExportsAsyncWithHttpInfo
     *
     * List all exports
     *
     * @param  string[] $type Filter exports by type (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExports'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getExportsAsyncWithHttpInfo($type, $page_number, $page_size, string $contentType = self::contentTypes['getExports'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedExports[]';
        $request = $this->getExportsRequest($type, $page_number, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getExports'
     *
     * @param  string[] $type Filter exports by type (required)
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getExports'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getExportsRequest($type, $page_number, $page_size, string $contentType = self::contentTypes['getExports'][0])
    {

        // verify the required parameter 'type' is set
        if ($type === null || (is_array($type) && count($type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $type when calling getExports'
            );
        }
        
        // verify the required parameter 'page_number' is set
        if ($page_number === null || (is_array($page_number) && count($page_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_number when calling getExports'
            );
        }
        if ($page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling ExportApi.getExports, must be bigger than or equal to 0.');
        }
        
        // verify the required parameter 'page_size' is set
        if ($page_size === null || (is_array($page_size) && count($page_size) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_size when calling getExports'
            );
        }
        if ($page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ExportApi.getExports, must be smaller than or equal to 100.');
        }
        if ($page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ExportApi.getExports, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/digital/v1/exports';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_number,
            'pageNumber', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
