<?php
/**
 * ScreeningApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Layer1ClientsDigitalInvoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Digital Asset
 *
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Layer1ClientsDigitalInvoker\Layer1ClientsDigitalApi;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Layer1ClientsDigitalInvoker\ApiException;
use Layer1ClientsDigitalInvoker\Configuration;
use Layer1ClientsDigitalInvoker\FormDataProcessor;
use Layer1ClientsDigitalInvoker\HeaderSelector;
use Layer1ClientsDigitalInvoker\ObjectSerializer;

/**
 * ScreeningApi Class Doc Comment
 *
 * @category Class
 * @package  Layer1ClientsDigitalInvoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScreeningApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'listScreenings' => [
            'application/json',
        ],
        'manuallyActionHeldTransfer' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation listScreenings
     *
     * List screening results
     *
     * @param  int $page_number page_number (required)
     * @param  int $page_size page_size (required)
     * @param  string|null $hash Filter by transaction hash (optional) (deprecated)
     * @param  string[]|null $operation Set of operations to filter by (optional) (deprecated)
     * @param  string[]|null $state Set of screening states to filter by (optional) (deprecated)
     * @param  \DateTime|null $start_date Start date for filtering by transfer creation date (optional) (deprecated)
     * @param  \DateTime|null $end_date End date for filtering by transfer creation date (optional) (deprecated)
     * @param  string|null $sort sort (optional, default to 'screeningId.transfer.id.createdAt,desc')
     * @param  string|null $q Query using Lucene-like syntax. Supported properties: notReasonCode, reasonCode, reason, hash, state, operation, from, to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScreenings'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedScreenings|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function listScreenings($page_number, $page_size, $hash = null, $operation = null, $state = null, $start_date = null, $end_date = null, $sort = 'screeningId.transfer.id.createdAt,desc', $q = null, string $contentType = self::contentTypes['listScreenings'][0])
    {
        list($response) = $this->listScreeningsWithHttpInfo($page_number, $page_size, $hash, $operation, $state, $start_date, $end_date, $sort, $q, $contentType);
        return $response;
    }

    /**
     * Operation listScreeningsWithHttpInfo
     *
     * List screening results
     *
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string|null $hash Filter by transaction hash (optional) (deprecated)
     * @param  string[]|null $operation Set of operations to filter by (optional) (deprecated)
     * @param  string[]|null $state Set of screening states to filter by (optional) (deprecated)
     * @param  \DateTime|null $start_date Start date for filtering by transfer creation date (optional) (deprecated)
     * @param  \DateTime|null $end_date End date for filtering by transfer creation date (optional) (deprecated)
     * @param  string|null $sort (optional, default to 'screeningId.transfer.id.createdAt,desc')
     * @param  string|null $q Query using Lucene-like syntax. Supported properties: notReasonCode, reasonCode, reason, hash, state, operation, from, to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScreenings'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedScreenings|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listScreeningsWithHttpInfo($page_number, $page_size, $hash = null, $operation = null, $state = null, $start_date = null, $end_date = null, $sort = 'screeningId.transfer.id.createdAt,desc', $q = null, string $contentType = self::contentTypes['listScreenings'][0])
    {
        $request = $this->listScreeningsRequest($page_number, $page_size, $hash, $operation, $state, $start_date, $end_date, $sort, $q, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedScreenings',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedScreenings',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedScreenings',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listScreeningsAsync
     *
     * List screening results
     *
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string|null $hash Filter by transaction hash (optional) (deprecated)
     * @param  string[]|null $operation Set of operations to filter by (optional) (deprecated)
     * @param  string[]|null $state Set of screening states to filter by (optional) (deprecated)
     * @param  \DateTime|null $start_date Start date for filtering by transfer creation date (optional) (deprecated)
     * @param  \DateTime|null $end_date End date for filtering by transfer creation date (optional) (deprecated)
     * @param  string|null $sort (optional, default to 'screeningId.transfer.id.createdAt,desc')
     * @param  string|null $q Query using Lucene-like syntax. Supported properties: notReasonCode, reasonCode, reason, hash, state, operation, from, to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScreenings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listScreeningsAsync($page_number, $page_size, $hash = null, $operation = null, $state = null, $start_date = null, $end_date = null, $sort = 'screeningId.transfer.id.createdAt,desc', $q = null, string $contentType = self::contentTypes['listScreenings'][0])
    {
        return $this->listScreeningsAsyncWithHttpInfo($page_number, $page_size, $hash, $operation, $state, $start_date, $end_date, $sort, $q, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listScreeningsAsyncWithHttpInfo
     *
     * List screening results
     *
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string|null $hash Filter by transaction hash (optional) (deprecated)
     * @param  string[]|null $operation Set of operations to filter by (optional) (deprecated)
     * @param  string[]|null $state Set of screening states to filter by (optional) (deprecated)
     * @param  \DateTime|null $start_date Start date for filtering by transfer creation date (optional) (deprecated)
     * @param  \DateTime|null $end_date End date for filtering by transfer creation date (optional) (deprecated)
     * @param  string|null $sort (optional, default to 'screeningId.transfer.id.createdAt,desc')
     * @param  string|null $q Query using Lucene-like syntax. Supported properties: notReasonCode, reasonCode, reason, hash, state, operation, from, to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScreenings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listScreeningsAsyncWithHttpInfo($page_number, $page_size, $hash = null, $operation = null, $state = null, $start_date = null, $end_date = null, $sort = 'screeningId.transfer.id.createdAt,desc', $q = null, string $contentType = self::contentTypes['listScreenings'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedScreenings';
        $request = $this->listScreeningsRequest($page_number, $page_size, $hash, $operation, $state, $start_date, $end_date, $sort, $q, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listScreenings'
     *
     * @param  int $page_number (required)
     * @param  int $page_size (required)
     * @param  string|null $hash Filter by transaction hash (optional) (deprecated)
     * @param  string[]|null $operation Set of operations to filter by (optional) (deprecated)
     * @param  string[]|null $state Set of screening states to filter by (optional) (deprecated)
     * @param  \DateTime|null $start_date Start date for filtering by transfer creation date (optional) (deprecated)
     * @param  \DateTime|null $end_date End date for filtering by transfer creation date (optional) (deprecated)
     * @param  string|null $sort (optional, default to 'screeningId.transfer.id.createdAt,desc')
     * @param  string|null $q Query using Lucene-like syntax. Supported properties: notReasonCode, reasonCode, reason, hash, state, operation, from, to (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScreenings'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listScreeningsRequest($page_number, $page_size, $hash = null, $operation = null, $state = null, $start_date = null, $end_date = null, $sort = 'screeningId.transfer.id.createdAt,desc', $q = null, string $contentType = self::contentTypes['listScreenings'][0])
    {

        // verify the required parameter 'page_number' is set
        if ($page_number === null || (is_array($page_number) && count($page_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_number when calling listScreenings'
            );
        }
        if ($page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling ScreeningApi.listScreenings, must be bigger than or equal to 0.');
        }
        
        // verify the required parameter 'page_size' is set
        if ($page_size === null || (is_array($page_size) && count($page_size) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_size when calling listScreenings'
            );
        }
        if ($page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ScreeningApi.listScreenings, must be smaller than or equal to 100.');
        }
        if ($page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ScreeningApi.listScreenings, must be bigger than or equal to 1.');
        }
        

        
        





        $resourcePath = '/digital/v1/screenings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $hash,
            'hash', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $operation,
            'operation', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $state,
            'state', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_date,
            'startDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_date,
            'endDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_number,
            'pageNumber', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation manuallyActionHeldTransfer
     *
     * Approve or reject a held transfer
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ManualActionRequest $manual_action_request manual_action_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manuallyActionHeldTransfer'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function manuallyActionHeldTransfer($manual_action_request, string $contentType = self::contentTypes['manuallyActionHeldTransfer'][0])
    {
        $this->manuallyActionHeldTransferWithHttpInfo($manual_action_request, $contentType);
    }

    /**
     * Operation manuallyActionHeldTransferWithHttpInfo
     *
     * Approve or reject a held transfer
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ManualActionRequest $manual_action_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manuallyActionHeldTransfer'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function manuallyActionHeldTransferWithHttpInfo($manual_action_request, string $contentType = self::contentTypes['manuallyActionHeldTransfer'][0])
    {
        $request = $this->manuallyActionHeldTransferRequest($manual_action_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation manuallyActionHeldTransferAsync
     *
     * Approve or reject a held transfer
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ManualActionRequest $manual_action_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manuallyActionHeldTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function manuallyActionHeldTransferAsync($manual_action_request, string $contentType = self::contentTypes['manuallyActionHeldTransfer'][0])
    {
        return $this->manuallyActionHeldTransferAsyncWithHttpInfo($manual_action_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation manuallyActionHeldTransferAsyncWithHttpInfo
     *
     * Approve or reject a held transfer
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ManualActionRequest $manual_action_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manuallyActionHeldTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function manuallyActionHeldTransferAsyncWithHttpInfo($manual_action_request, string $contentType = self::contentTypes['manuallyActionHeldTransfer'][0])
    {
        $returnType = '';
        $request = $this->manuallyActionHeldTransferRequest($manual_action_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'manuallyActionHeldTransfer'
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ManualActionRequest $manual_action_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['manuallyActionHeldTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function manuallyActionHeldTransferRequest($manual_action_request, string $contentType = self::contentTypes['manuallyActionHeldTransfer'][0])
    {

        // verify the required parameter 'manual_action_request' is set
        if ($manual_action_request === null || (is_array($manual_action_request) && count($manual_action_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $manual_action_request when calling manuallyActionHeldTransfer'
            );
        }


        $resourcePath = '/digital/v1/screenings/action';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($manual_action_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($manual_action_request));
            } else {
                $httpBody = $manual_action_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
