<?php
/**
 * TransactionRequestApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Layer1ClientsDigitalInvoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Digital Asset
 *
 * Layer1 API making management of crypto assets simple and easy
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Layer1ClientsDigitalInvoker\Layer1ClientsDigitalApi;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Layer1ClientsDigitalInvoker\ApiException;
use Layer1ClientsDigitalInvoker\Configuration;
use Layer1ClientsDigitalInvoker\FormDataProcessor;
use Layer1ClientsDigitalInvoker\HeaderSelector;
use Layer1ClientsDigitalInvoker\ObjectSerializer;

/**
 * TransactionRequestApi Class Doc Comment
 *
 * @category Class
 * @package  Layer1ClientsDigitalInvoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionRequestApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createStakingTransaction' => [
            'application/json',
        ],
        'createTransaction' => [
            'application/json',
        ],
        'getTransactionRequestById' => [
            'application/json',
        ],
        'listTransactionRequests' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createStakingTransaction
     *
     * Create staking transaction request
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateStakingTransactionRequest $create_staking_transaction_request create_staking_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStakingTransaction'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function createStakingTransaction($create_staking_transaction_request, string $contentType = self::contentTypes['createStakingTransaction'][0])
    {
        list($response) = $this->createStakingTransactionWithHttpInfo($create_staking_transaction_request, $contentType);
        return $response;
    }

    /**
     * Operation createStakingTransactionWithHttpInfo
     *
     * Create staking transaction request
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateStakingTransactionRequest $create_staking_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStakingTransaction'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createStakingTransactionWithHttpInfo($create_staking_transaction_request, string $contentType = self::contentTypes['createStakingTransaction'][0])
    {
        $request = $this->createStakingTransactionRequest($create_staking_transaction_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createStakingTransactionAsync
     *
     * Create staking transaction request
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateStakingTransactionRequest $create_staking_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStakingTransaction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStakingTransactionAsync($create_staking_transaction_request, string $contentType = self::contentTypes['createStakingTransaction'][0])
    {
        return $this->createStakingTransactionAsyncWithHttpInfo($create_staking_transaction_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createStakingTransactionAsyncWithHttpInfo
     *
     * Create staking transaction request
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateStakingTransactionRequest $create_staking_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStakingTransaction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStakingTransactionAsyncWithHttpInfo($create_staking_transaction_request, string $contentType = self::contentTypes['createStakingTransaction'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest';
        $request = $this->createStakingTransactionRequest($create_staking_transaction_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createStakingTransaction'
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateStakingTransactionRequest $create_staking_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStakingTransaction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createStakingTransactionRequest($create_staking_transaction_request, string $contentType = self::contentTypes['createStakingTransaction'][0])
    {

        // verify the required parameter 'create_staking_transaction_request' is set
        if ($create_staking_transaction_request === null || (is_array($create_staking_transaction_request) && count($create_staking_transaction_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_staking_transaction_request when calling createStakingTransaction'
            );
        }


        $resourcePath = '/digital/v1/staking-requests';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_staking_transaction_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_staking_transaction_request));
            } else {
                $httpBody = $create_staking_transaction_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createTransaction
     *
     * Create transaction request
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateTransactionRequest $create_transaction_request create_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTransaction'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function createTransaction($create_transaction_request, string $contentType = self::contentTypes['createTransaction'][0])
    {
        list($response) = $this->createTransactionWithHttpInfo($create_transaction_request, $contentType);
        return $response;
    }

    /**
     * Operation createTransactionWithHttpInfo
     *
     * Create transaction request
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateTransactionRequest $create_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTransaction'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createTransactionWithHttpInfo($create_transaction_request, string $contentType = self::contentTypes['createTransaction'][0])
    {
        $request = $this->createTransactionRequest($create_transaction_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createTransactionAsync
     *
     * Create transaction request
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateTransactionRequest $create_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTransaction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createTransactionAsync($create_transaction_request, string $contentType = self::contentTypes['createTransaction'][0])
    {
        return $this->createTransactionAsyncWithHttpInfo($create_transaction_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createTransactionAsyncWithHttpInfo
     *
     * Create transaction request
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateTransactionRequest $create_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTransaction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createTransactionAsyncWithHttpInfo($create_transaction_request, string $contentType = self::contentTypes['createTransaction'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest';
        $request = $this->createTransactionRequest($create_transaction_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createTransaction'
     *
     * @param  \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\CreateTransactionRequest $create_transaction_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createTransaction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createTransactionRequest($create_transaction_request, string $contentType = self::contentTypes['createTransaction'][0])
    {

        // verify the required parameter 'create_transaction_request' is set
        if ($create_transaction_request === null || (is_array($create_transaction_request) && count($create_transaction_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_transaction_request when calling createTransaction'
            );
        }


        $resourcePath = '/digital/v1/transaction-requests';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_transaction_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_transaction_request));
            } else {
                $httpBody = $create_transaction_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTransactionRequestById
     *
     * Get transaction request
     *
     * @param  string $request_id request_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionRequestById'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function getTransactionRequestById($request_id, string $contentType = self::contentTypes['getTransactionRequestById'][0])
    {
        list($response) = $this->getTransactionRequestByIdWithHttpInfo($request_id, $contentType);
        return $response;
    }

    /**
     * Operation getTransactionRequestByIdWithHttpInfo
     *
     * Get transaction request
     *
     * @param  string $request_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionRequestById'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTransactionRequestByIdWithHttpInfo($request_id, string $contentType = self::contentTypes['getTransactionRequestById'][0])
    {
        $request = $this->getTransactionRequestByIdRequest($request_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getTransactionRequestByIdAsync
     *
     * Get transaction request
     *
     * @param  string $request_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionRequestById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionRequestByIdAsync($request_id, string $contentType = self::contentTypes['getTransactionRequestById'][0])
    {
        return $this->getTransactionRequestByIdAsyncWithHttpInfo($request_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTransactionRequestByIdAsyncWithHttpInfo
     *
     * Get transaction request
     *
     * @param  string $request_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionRequestById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTransactionRequestByIdAsyncWithHttpInfo($request_id, string $contentType = self::contentTypes['getTransactionRequestById'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\TransactionRequest';
        $request = $this->getTransactionRequestByIdRequest($request_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTransactionRequestById'
     *
     * @param  string $request_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTransactionRequestById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTransactionRequestByIdRequest($request_id, string $contentType = self::contentTypes['getTransactionRequestById'][0])
    {

        // verify the required parameter 'request_id' is set
        if ($request_id === null || (is_array($request_id) && count($request_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request_id when calling getTransactionRequestById'
            );
        }


        $resourcePath = '/digital/v1/transaction-requests/{requestId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($request_id !== null) {
            $resourcePath = str_replace(
                '{' . 'requestId' . '}',
                ObjectSerializer::toPathValue($request_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listTransactionRequests
     *
     * List transaction requests
     *
     * @param  string $asset_pool_id asset pool id (required)
     * @param  int $page_number current page number (required)
     * @param  int $page_size number of items in a page (required)
     * @param  string|null $q Query in lucene like format, e.g. reference:REF-12a1. Supported properties: reference, type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTransactionRequests'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultTransactionRequest|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError
     */
    public function listTransactionRequests($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listTransactionRequests'][0])
    {
        list($response) = $this->listTransactionRequestsWithHttpInfo($asset_pool_id, $page_number, $page_size, $q, $contentType);
        return $response;
    }

    /**
     * Operation listTransactionRequestsWithHttpInfo
     *
     * List transaction requests
     *
     * @param  string $asset_pool_id asset pool id (required)
     * @param  int $page_number current page number (required)
     * @param  int $page_size number of items in a page (required)
     * @param  string|null $q Query in lucene like format, e.g. reference:REF-12a1. Supported properties: reference, type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTransactionRequests'] to see the possible values for this operation
     *
     * @throws \Layer1ClientsDigitalInvoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultTransactionRequest|\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listTransactionRequestsWithHttpInfo($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listTransactionRequests'][0])
    {
        $request = $this->listTransactionRequestsRequest($asset_pool_id, $page_number, $page_size, $q, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 503:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultTransactionRequest',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultTransactionRequest',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 503:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultTransactionRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listTransactionRequestsAsync
     *
     * List transaction requests
     *
     * @param  string $asset_pool_id asset pool id (required)
     * @param  int $page_number current page number (required)
     * @param  int $page_size number of items in a page (required)
     * @param  string|null $q Query in lucene like format, e.g. reference:REF-12a1. Supported properties: reference, type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTransactionRequests'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listTransactionRequestsAsync($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listTransactionRequests'][0])
    {
        return $this->listTransactionRequestsAsyncWithHttpInfo($asset_pool_id, $page_number, $page_size, $q, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listTransactionRequestsAsyncWithHttpInfo
     *
     * List transaction requests
     *
     * @param  string $asset_pool_id asset pool id (required)
     * @param  int $page_number current page number (required)
     * @param  int $page_size number of items in a page (required)
     * @param  string|null $q Query in lucene like format, e.g. reference:REF-12a1. Supported properties: reference, type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTransactionRequests'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listTransactionRequestsAsyncWithHttpInfo($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listTransactionRequests'][0])
    {
        $returnType = '\Layer1ClientsDigitalInvoker\Layer1ClientsDigitalModel\PaginatedResultTransactionRequest';
        $request = $this->listTransactionRequestsRequest($asset_pool_id, $page_number, $page_size, $q, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listTransactionRequests'
     *
     * @param  string $asset_pool_id asset pool id (required)
     * @param  int $page_number current page number (required)
     * @param  int $page_size number of items in a page (required)
     * @param  string|null $q Query in lucene like format, e.g. reference:REF-12a1. Supported properties: reference, type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listTransactionRequests'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listTransactionRequestsRequest($asset_pool_id, $page_number, $page_size, $q = null, string $contentType = self::contentTypes['listTransactionRequests'][0])
    {

        // verify the required parameter 'asset_pool_id' is set
        if ($asset_pool_id === null || (is_array($asset_pool_id) && count($asset_pool_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $asset_pool_id when calling listTransactionRequests'
            );
        }

        // verify the required parameter 'page_number' is set
        if ($page_number === null || (is_array($page_number) && count($page_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_number when calling listTransactionRequests'
            );
        }
        if ($page_number < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling TransactionRequestApi.listTransactionRequests, must be bigger than or equal to 0.');
        }
        
        // verify the required parameter 'page_size' is set
        if ($page_size === null || (is_array($page_size) && count($page_size) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $page_size when calling listTransactionRequests'
            );
        }
        if ($page_size > 500) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling TransactionRequestApi.listTransactionRequests, must be smaller than or equal to 500.');
        }
        if ($page_size < 0) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling TransactionRequestApi.listTransactionRequests, must be bigger than or equal to 0.');
        }
        


        $resourcePath = '/digital/v1/transaction-requests';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $asset_pool_id,
            'assetPoolId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_number,
            'pageNumber', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
